version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - database
    networks:
      - auth-lab

  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=authlab
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-lab

volumes:
  postgres_data:

networks:
  auth-lab:
    driver: bridge
